create or replace TABLE fake_db.fake_schema.DATEDCONVERSIONRATE (
    ID VARCHAR(18) NOT NULL,
    ISOCODE VARCHAR(40),
    STARTDATE DATE,
    NEXTSTARTDATE DATE,
    CONVERSIONRATE NUMBER(18,6),
    CREATEDDATE TIMESTAMP_NTZ(9),
    CREATEDBYID VARCHAR(18),
    LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
    LASTMODIFIEDBYID VARCHAR(18),
    SYSTEMMODTIMESTAMP TIMESTAMP_NTZ(9),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    DQ_VALID BOOLEAN,
    primary key (ID)
);