create or replace TABLE fake_db.fake_schema.OPPORTUNITYTEAMMEMBER (
    ID VARCHAR(18) NOT NULL,
    OPPORTUNITYID VARCHAR(18),
    USERID VARCHAR(18),
    NAME VARCHAR(361),
    PHOTOURL VARCHAR(255),
    TITLE VARCHAR(80),
    TEAMMEMBERROLE VARCHAR(255),
    OPPORTUNITYACCESSLEVEL VARCHAR(40),
    CURRENCYISOCODE VARCHAR(3),
    CREATEDDATE TIMESTAMP_NTZ(9),
    CREATEDBYID VARCHAR(18),
    LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
    LASTMODIFIEDBYID VARCHAR(18),
    SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
    ISDELETED BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    primary key (ID)
);