create or replace TABLE fake_db.fake_schema.OPPORTUNITYCONTACTROLE (
    ID VARCHAR(18) NOT NULL,
    OPPORTUNITYID VARCHAR(18),
    CONTACTID VARCHAR(18),
    ROLE VARCHAR(255),
    ISPRIMARY BOOLEAN,
    CREATEDDATE TIMESTAMP_NTZ(9),
    CREATEDBYID VARCHAR(18),
    LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
    LASTMODIFIEDBYID VARCHAR(18),
    SYSTEMMODSTAMP TIMESTAMP_NTZ(9),
    ISDELETED BOOLEAN,
    CURRENCYISOCODE VARCHAR(3),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    primary key (ID)
);