create or replace TABLE fake_db.fake_schema.OPPORTUNITYFIELDHISTORY (
    ID VARCHAR(18) NOT NULL,
    ISDELETED BOOLEAN,
    OPPORTUNITYID VARCHAR(18),
    CREATEDBYID VARCHAR(18),
    CREATEDDATE TIMESTAMP_NTZ(9),
    FIELD VARCHAR(255),
    DATATYPE VARCHAR(40),
    OLDVALUE VARCHAR(255),
    NEWVALUE VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    primary key (ID)
);