create or replace TABLE fake_db.fake_schema.opportunity (
    --ID Fields
    ID VARCHAR(18) NOT NULL,
    X18_DIGIT_OPPORTUNITY_ID__C VARCHAR(1300),
    ACCOUNT_ID VARCHAR(18),
    ACCOUNT_KEY VARCHAR(28),
    OPPORTUNITY_KEY VARCHAR(28) NOT NULL,
    OWNER_KEY VARCHAR(28),
    SALESFORCE_ACCOUNT_ID VARCHAR(15),
    OWNER_ID VARCHAR(18),

    --Detail Fields
    NAME VARCHAR(120),
    DESCRIPTION VARCHAR(32000),
    COPY_OPPORTUNITY_RECORD_TYPE VARCHAR(1300),
    TYPE VARCHAR(40),
    TYPE_OF_UPSELL VARCHAR(4099),
    SALES_REGION VARCHAR(255),
    OPPORTUNITY_SOURCE VARCHAR(255),
    AMOUNT NUMBER(18,2),
    NORAM_AIR_VOLUME NUMBER(18,0),
    GRAND_TOTAL_OF_GLOBAL_OPPORTUNITY NUMBER(18,0),
    CURRENCYISOCODE VARCHAR(3),
    
    --Status Fields
    STAGE_NAME VARCHAR(40),
    PROBABILITY NUMBER (3,0),
    CLOSE_DATE TIMESTAMP_NTZ(9),
    CLOSED_DATE NUMBER(28,0),
    FORECASTCATEGORY VARCHAR(40), -- THIS MAY NEED TO BE FORECASTCATEGORYNAME
    FORECAST_HEALTH VARCHAR(255),
    FORECAST_COMMITTED VARCHAR(255),
    IS_DELETED BOOLEAN,
    IS_CLOSED BOOLEAN,
    IS_WON BOOLEAN,
    
    --Post-Win Implementation Fields
    IMPLEMENTATION_STATUS VARCHAR(50),
    IMPLEMENTATION_GO_LIVE_DATE TIMESTAMP_NTZ(9),
    DT_IMPLEMENTATION_READY_DATE TIMESTAMP_NTZ(9),
    ACTUAL_IMPLEMENTATION_DATE TIMESTAMP_NTZ(9),
    
    --Audit Fields
    CREATED_DATE TIMESTAMP_NTZ(9),
    CREATED_BY_ID VARCHAR(18),
    LAST_MODIFIED_DATE TIMESTAMP_NTZ(9),
    LAST_MODIFIED_BY_ID VARCHAR(18),

    --Constraints
    PRIMARY KEY (OPPORTUNITY_KEY)
);