create or replace TABLE fake_db.fake_schema.user (
    ID VARCHAR(18) NOT NULL,
    USER_KEY VARCHAR(28) NOT NULL,
    USER_NAME VARCHAR(80),
    FIRST_NAME VARCHAR(40),
    LAST_NAME VARCHAR(80),
    NAME VARCHAR(121),
    EMAIL VARCHAR(128),
    MANAGER_ID VARCHAR(255),
    IS_BADGED BOOLEAN,
    IS_ACTIVE BOOLEAN,
    REGION VARCHAR(255),
    ROLE_NAME VARCHAR(1300),
    PRIMARY KEY (USER_KEY)
);